os:
  - osx
script:
  - flutter doctor && cd example && flutter test
before_install:
    - git clone -b 'v1.5.4-hotfix.2' --depth 1 https://github.com/flutter/flutter.git
    - export PATH="$PATH:`pwd`/flutter/bin"
